hs_passwordless_register:
    pattern: /register
    defaults: { _controller: HSPasswordLessBundle:Registration:register }

hs_passwordless_confirm_registration:
    pattern: /register/confirm/{hash}
    defaults: { _controller: HSPasswordLessBundle:Registration:confirmRegistration }

hs_passwordless_request_login:
    pattern: /request-login
    defaults: { _controller: HSPasswordLessBundle:Security:loginRequest }

hs_passwordless_confirm_login:
    pattern: /confirm-login/{hash}
    defaults: { _controller: HSPasswordLessBundle:Security:confirmLogin }
