juma_ping.api.players_list:
    pattern: /players
    defaults: { _controller: JUMAPingBundle:Player:list }
    methods:  [GET]
    condition: "request.isXmlHttpRequest()"
    requirements:
        _format:  json

juma_ping.api.player_ratings:
    pattern: /player/{id}/rating
    defaults: { _controller: JUMAPingBundle:Player:playerRatings }
    methods:  [GET]
    requirements:
        _format:  json
