juma_ping.rating_list:
    pattern: /
    defaults: { _controller: JUMAPingBundle:Rating:list }

juma_ping.rating_player:
    pattern: /player/{id}
    defaults: { _controller: JUMAPingBundle:Rating:player }